const EErrors = {
    ROUTING_ERROR: 1,
    USER__NULL_CREDENTIALS__ERROR: 2,
    USER__FAKE_CREDENTIALS__ERROR: 3,
    USER__PERMISION_CREDENTIALS__ERROR: 4,

    USER__NULL_DATA__ERROR: 5,
    USER__WRONG_DATA__ERROR: 6,
    USER__MISS_DATA__ERROR: 7,

    INVALID_TYPES_ERROR: 8,
    DATA_BASE__ERROR: 9,
};

module.exports = EErrors;
